# wrangler.toml
name = 'et21workers'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
[vars]
URL = "misub.52013130.xyz"
#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id
[[kv_namespaces]]
binding = "KV"
id = "35c03c41e93643e595c2e326ffb7d7ef"
